<?php
return array (
  'catid' => 
  array (
    'fieldid' => '280',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'catid',
    'name' => '栏目',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '6',
    'pattern' => '/^[0-9]{1,6}$/',
    'errortips' => '请选择栏目',
    'formtype' => 'catid',
    'setting' => '{"defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'defaultvalue' => '',
  ),
  'typeid' => 
  array (
    'fieldid' => '281',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'typeid',
    'name' => '类别',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'typeid',
    'setting' => '{"minnumber":"","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '',
    'defaultvalue' => '',
  ),
  'title' => 
  array (
    'fieldid' => '282',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'title',
    'name' => '单位全称',
    'tips' => '',
    'css' => 'inputtitle',
    'minlength' => '1',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '请输入标题',
    'formtype' => 'title',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '3',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'website' => 
  array (
    'fieldid' => '532',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'website',
    'name' => '官网地址',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'place' => 
  array (
    'fieldid' => '313',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'place',
    'name' => '办公地址',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => '{"linkageid":"1","showtype":"1","space":"-","filtertype":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '1',
    'showtype' => '1',
    'space' => '-',
    'filtertype' => '1',
  ),
  'industry' => 
  array (
    'fieldid' => '301',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'industry',
    'name' => '所属行业',
    'tips' => ' ',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u8bc1\\u5238\\u516c\\u53f8|1\\r\\n\\u4f1a\\u8ba1\\u5e08\\u4e8b\\u52a1\\u6240|2\\r\\n\\u8d44\\u4ea7\\u8bc4\\u4f30\\u673a\\u6784|3\\r\\n\\u5f8b\\u5e08\\u4e8b\\u52a1\\u6240|4\\r\\n\\u4fe1\\u7528\\u8bc4\\u7ea7\\u673a\\u6784|5\\r\\n\\u8d22\\u52a1\\u987e\\u95ee\\u516c\\u53f8|6\\r\\n\\u7ba1\\u7406\\u54a8\\u8be2\\u516c\\u53f8|7\\r\\n\\u4ea7\\u4e1a\\u54a8\\u8be2\\u516c\\u53f8|8\\r\\nIPO\\u54a8\\u8be2\\u516c\\u53f8|9\\r\\n\\u8d22\\u7ecf\\u516c\\u5173\\u516c\\u53f8|10\\r\\n\\u4f20\\u64ad\\/\\u76d1\\u6d4b\\u516c\\u53f8|11\\r\\n\\u5a92\\u4f53|12\\r\\n\\u7f51\\u4e0a\\u8def\\u6f14\\u5e73\\u53f0|13\\r\\n\\u6444\\u5f71\\u6444\\u50cf\\u516c\\u53f8|14\\r\\n\\u5e7f\\u544a\\u516c\\u53f8|15\\r\\n\\u8bbe\\u8ba1\\/\\u5370\\u5237\\u516c\\u53f8|16\\r\\n\\u7ffb\\u8bd1\\u516c\\u53f8|17\\r\\n\\u4fe1\\u606f\\u8f6f\\u4ef6\\u516c\\u53f8|18","boxtype":"radio","fieldtype":"varchar","minnumber":"1","width":"120","size":"1","defaultvalue":"1","outputtype":"0","filtertype":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '8',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '证券公司|1
会计师事务所|2
资产评估机构|3
律师事务所|4
信用评级机构|5
财务顾问公司|6
管理咨询公司|7
产业咨询公司|8
IPO咨询公司|9
财经公关公司|10
传播/监测公司|11
媒体|12
网上路演平台|13
摄影摄像公司|14
广告公司|15
设计/印刷公司|16
翻译公司|17
信息软件公司|18',
    'boxtype' => 'radio',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '120',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
    'filtertype' => '1',
  ),
  'item' => 
  array (
    'fieldid' => '602',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'item',
    'name' => '服务项目',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u6295\\u8d44\\u94f6\\u884c|1\\r\\n\\u8d44\\u4ea7\\u8bc4\\u4f30|2\\r\\n\\u4f1a\\u8ba1\\u4e8b\\u52a1\\u6240|3\\r\\n\\u5f8b\\u5e08\\u4e8b\\u52a1\\u6240|4\\r\\nIPO\\u54a8\\u8be2|11\\r\\nIPO\\u8d22\\u52a1\\u987e\\u95ee|12\\r\\n\\u52df\\u6295\\u53ca\\u884c\\u4e1a\\u53ef\\u7814|13\\r\\nIPO\\u8d22\\u7ecf\\u516c\\u5173|14\\r\\n\\u516c\\u53f8\\u503a\\u8d22\\u987e|21\\r\\n\\u8d44\\u4ea7\\u8bc1\\u5238\\u5316\\u8d22\\u987e|22\\r\\n\\u77ed\\u671f\\u878d\\u8d44\\u5238\\u8d22\\u987e|23\\r\\n\\u4fe1\\u7528\\u8bc4\\u7ea7|24\\r\\n\\u80a1\\u6743\\u8d28\\u62bc\\u878d\\u8d44|31\\r\\n\\u5927\\u5b97\\u4ea4\\u6613\\u670d\\u52a1|32\\r\\n\\u7a0e\\u6536\\u7b79\\u5212|33\\r\\n\\u5e76\\u8d2d\\u91cd\\u7ec4\\u8d22\\u987e|34\\r\\n\\u8bbe\\u7acb\\u5e76\\u8d2d\\u57fa\\u91d1|35\\r\\n\\u56de\\u8d2d\\u4ee3\\u64cd\\u76d8|41\\r\\n\\u80a1\\u6743\\u6fc0\\u52b1\\u987e\\u95ee|51\\r\\n\\u80a1\\u6743\\u6fc0\\u52b1\\u884c\\u6743\\u7cfb\\u7edf|52\\r\\n\\u5408\\u89c4\\u4e0e\\u4fe1\\u62ab\\u54a8\\u8be2|53\\r\\n\\u5185\\u90e8\\u63a7\\u5236\\u54a8\\u8be2|54\\r\\n\\u793e\\u4f1a\\u8d23\\u4efb\\u54a8\\u8be2|55\\r\\n\\u8bc1\\u5238\\u4e8b\\u52a1\\u8f6f\\u4ef6|56\\r\\n\\u8d22\\u7ecf\\u516c\\u5173|57\\r\\n\\u5371\\u673a\\u516c\\u5173|58\\r\\n\\u5a92\\u4f53\\u76d1\\u6d4b|59\\r\\n\\u65b0\\u95fb\\u4f20\\u64ad|60\\r\\n\\u6295\\u8d44\\u8005\\u5173\\u7cfb|61\\r\\nIR\\u5e73\\u53f0\\u5efa\\u8bbe|62\\r\\n\\u73b0\\u573a\\u8def\\u6f14\\u670d\\u52a1|63\\r\\n\\u7f51\\u4e0a\\u8def\\u6f14\\u5e73\\u53f0|64\\r\\n\\u5e02\\u503c\\u7ba1\\u7406|65\\r\\n\\u9ad8\\u7ba1\\u8d23\\u4efb\\u9669|66\\r\\n\\u91d1\\u878d\\u4fe1\\u606f\\u8f6f\\u4ef6|71\\r\\n\\u8d22\\u7ecf\\u5370\\u5237|72\\r\\n\\u516c\\u53f8\\u5ba3\\u4f20\\u7247|73\\r\\n\\u5927\\u578b\\u9152\\u4f1a\\u670d\\u52a1|74\\r\\n\\u5de5\\u827a\\u793c\\u54c1|75","boxtype":"checkbox","fieldtype":"varchar","minnumber":"1","width":"120","size":"1","defaultvalue":"","outputtype":"1","filtertype":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '9',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '投资银行|1
资产评估|2
会计事务所|3
律师事务所|4
IPO咨询|11
IPO财务顾问|12
募投及行业可研|13
IPO财经公关|14
公司债财顾|21
资产证券化财顾|22
短期融资券财顾|23
信用评级|24
股权质押融资|31
大宗交易服务|32
税收筹划|33
并购重组财顾|34
设立并购基金|35
回购代操盘|41
股权激励顾问|51
股权激励行权系统|52
合规与信披咨询|53
内部控制咨询|54
社会责任咨询|55
证券事务软件|56
财经公关|57
危机公关|58
媒体监测|59
新闻传播|60
投资者关系|61
IR平台建设|62
现场路演服务|63
网上路演平台|64
市值管理|65
高管责任险|66
金融信息软件|71
财经印刷|72
公司宣传片|73
大型酒会服务|74
工艺礼品|75',
    'boxtype' => 'checkbox',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '120',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '0',
  ),
  'content' => 
  array (
    'fieldid' => '286',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'content',
    'name' => '业务介绍',
    'tips' => '<div class="content_attr"><label><input name="add_introduce" type="checkbox"  value="1">是否截取内容</label><input type="text" name="introcude_length" value="200" size="3">字符至内容摘要
<label><input type=\'checkbox\' name=\'auto_thumb\' value="1">是否获取内容第</label><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为标题图片
</div>',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '999999',
    'pattern' => '',
    'errortips' => '内容不能为空',
    'formtype' => 'editor',
    'setting' => '{"toolbar":"full","defaultvalue":"","enablekeylink":"1","replacenum":"2","link_mode":"0","enablesaveimage":"1","height":"","disabled_page":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '20',
    'disabled' => '0',
    'isomnipotent' => '0',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '1',
    'replacenum' => '2',
    'link_mode' => '0',
    'enablesaveimage' => '1',
    'height' => '',
    'disabled_page' => '0',
  ),
  'contact' => 
  array (
    'fieldid' => '604',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'contact',
    'name' => '联系人员',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => '{"toolbar":"basic","defaultvalue":"","enablekeylink":"0","replacenum":"1","link_mode":"0","enablesaveimage":"0","height":"200"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '21',
    'disabled' => '0',
    'isomnipotent' => '0',
    'toolbar' => 'basic',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '200',
  ),
  'address' => 
  array (
    'fieldid' => '303',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'address',
    'name' => '办公地址',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'map',
    'setting' => '{"maptype":"2","api_key":"","defaultcity":"\\u6df1\\u5733","hotcitys":"","width":"","height":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '22',
    'disabled' => '0',
    'isomnipotent' => '0',
    'maptype' => '2',
    'api_key' => '',
    'defaultcity' => '深圳',
    'hotcitys' => '',
    'width' => '',
    'height' => '',
  ),
  'inputtime' => 
  array (
    'fieldid' => '290',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'inputtime',
    'name' => '发布时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => '{"fieldtype":"int","format":"Y-m-d H:i:s","defaulttype":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '23',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '0',
  ),
  'posids' => 
  array (
    'fieldid' => '291',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'posids',
    'name' => '推荐位',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'posid',
    'setting' => '{"cols":"4","width":"125"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '26',
    'disabled' => '0',
    'isomnipotent' => '0',
    'cols' => '4',
    'width' => '125',
  ),
  'islink' => 
  array (
    'fieldid' => '300',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'islink',
    'name' => '转向链接',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'islink',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '28',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'thumb' => 
  array (
    'fieldid' => '287',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'thumb',
    'name' => '缩略图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => '{"size":"50","defaultvalue":"","show_type":"1","upload_maxsize":"1024","upload_allowext":"jpg|jpeg|gif|png|bmp","watermark":"0","isselectimage":"1","images_width":"","images_height":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '31',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'show_type' => '1',
    'upload_maxsize' => '1024',
    'upload_allowext' => 'jpg|jpeg|gif|png|bmp',
    'watermark' => '0',
    'isselectimage' => '1',
    'images_width' => '',
    'images_height' => '',
  ),
  'updatetime' => 
  array (
    'fieldid' => '285',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'updatetime',
    'name' => '更新时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => '{"dateformat":"int","format":"Y-m-d H:i:s","defaulttype":"1","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '32',
    'disabled' => '0',
    'isomnipotent' => '0',
    'dateformat' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '1',
    'defaultvalue' => '',
  ),
  'relation' => 
  array (
    'fieldid' => '288',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'relation',
    'name' => '相关文章',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => '{"formtext":"<input type=\'hidden\' name=\'info[relation]\' id=\'relation\' value=\'{FIELD_VALUE}\' style=\'50\' >\\r\\n<ul class=\\"list-dot\\" id=\\"relation_text\\"><\\/ul>\\r\\n<div>\\r\\n<input type=\'button\' value=\\"\\u6dfb\\u52a0\\u76f8\\u5173\\" onclick=\\"omnipotent(\'selectid\',\'?m=content&c=content&a=public_relationlist&modelid={MODELID}\',\'\\u6dfb\\u52a0\\u76f8\\u5173\\u6587\\u7ae0\',1)\\" class=\\"button\\" style=\\"width:66px;\\">\\r\\n<span class=\\"edit_content\\">\\r\\n<input type=\'button\' value=\\"\\u663e\\u793a\\u5df2\\u6709\\" onclick=\\"show_relation({MODELID},{ID})\\" class=\\"button\\" style=\\"width:66px;\\">\\r\\n<\\/span>\\r\\n<\\/div>","fieldtype":"varchar","minnumber":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '2,6,4,5,1,17,18,7',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '33',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<input type=\'hidden\' name=\'info[relation]\' id=\'relation\' value=\'{FIELD_VALUE}\' style=\'50\' >
<ul class="list-dot" id="relation_text"></ul>
<div>
<input type=\'button\' value="添加相关" onclick="omnipotent(\'selectid\',\'?m=content&c=content&a=public_relationlist&modelid={MODELID}\',\'添加相关文章\',1)" class="button" style="width:66px;">
<span class="edit_content">
<input type=\'button\' value="显示已有" onclick="show_relation({MODELID},{ID})" class="button" style="width:66px;">
</span>
</div>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'url' => 
  array (
    'fieldid' => '293',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'url',
    'name' => 'URL',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '50',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'listorder' => 
  array (
    'fieldid' => '294',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'listorder',
    'name' => '排序',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '6',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '51',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'template' => 
  array (
    'fieldid' => '295',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'template',
    'name' => '内容页模板',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '30',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => '{"size":"","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '53',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '',
    'defaultvalue' => '',
  ),
  'allow_comment' => 
  array (
    'fieldid' => '296',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'allow_comment',
    'name' => '允许评论',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u5141\\u8bb8\\u8bc4\\u8bba|1\\r\\n\\u4e0d\\u5141\\u8bb8\\u8bc4\\u8bba|0","boxtype":"radio","fieldtype":"tinyint","minnumber":"1","width":"88","size":"1","defaultvalue":"1","outputtype":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '54',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '允许评论|1
不允许评论|0',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '88',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
  ),
  'status' => 
  array (
    'fieldid' => '297',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'status',
    'name' => '状态',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '2',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '55',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'username' => 
  array (
    'fieldid' => '299',
    'modelid' => '18',
    'siteid' => '1',
    'field' => 'username',
    'name' => '用户名',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '20',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '98',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
);
?>