<?php
return array (
  2 => 
  array (
    'posid' => '2',
    'modelid' => '1',
    'catid' => '13',
    'name' => '监管中心',
    'maxnum' => '10',
    'extention' => '',
    'listorder' => '4',
    'siteid' => '1',
    'thumb' => '',
  ),
  1 => 
  array (
    'posid' => '1',
    'modelid' => '1',
    'catid' => '12',
    'name' => '资讯中心',
    'maxnum' => '10',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '1',
    'catid' => '312',
    'name' => '会所新闻',
    'maxnum' => '10',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '1',
    'catid' => '314',
    'name' => '律所新闻',
    'maxnum' => '10',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '3',
    'catid' => '0',
    'name' => '视频首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '3',
    'catid' => '0',
    'name' => '首页图片推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '3',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '3',
    'catid' => '0',
    'name' => '网站顶部推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '3',
    'catid' => '0',
    'name' => '图片频道首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '1',
    'catid' => '14',
    'name' => '智库',
    'maxnum' => '10',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '3',
    'catid' => '0',
    'name' => '栏目页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '1',
    'catid' => '310',
    'name' => '投行新闻',
    'maxnum' => '10',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>